version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mydatabase
    ports:
      - '27017:27017'
    command:
      [
        '--replSet',
        'rs0',
        '--bind_ip_all',
        '--auth',
        '--keyFile',
        '/data/configdb/mongo-keyfile',
      ]
    volumes:
      - mongodb_data:/data/db
      - ./keyFile:/data/configdb/mongo-keyfile
    networks:
      - mongo-network

volumes:
  mongodb_data:
    driver: local
networks:
  mongo-network:
    driver: bridge
